auto_scale_lr = dict(base_batch_size=48, enable=False)
backend_args = None
class_names = [
    'Car',
]
code_weights = [
    2.0,
    2.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    0.0,
    0.0,
    0.0,
]
custom_imports = dict(
    allow_failed_imports=False,
    imports=[
        'projects.myfusion.pipelines.limit_samples',
        'mmdet.models',
        'mmdet.models.losses',
        'projects.myfusion.fusion.my_fusion',
        'projects.myfusion.fusion.mbt',
        'projects.myfusion.datasets.kitti_fusion_dataset',
    ])
data = dict(
    test=dict(
        batch_size=1,
        dataset=dict(
            ann_file='kitti_infos_val.pkl',
            backend_args=None,
            box_type_3d='LiDAR',
            data_prefix=dict(
                img='training/image_2', pts='training/velodyne_reduced'),
            data_root='data/kitti/',
            metainfo=dict(classes=[
                'Car',
            ]),
            modality=dict(use_camera=True, use_lidar=True),
            pipeline=[
                dict(type='mmcv.LoadImageFromFile'),
                dict(keep_ratio=False, scale=(
                    1280,
                    384,
                ), type='Resize'),
                dict(
                    mean=[
                        123.675,
                        116.28,
                        103.53,
                    ],
                    std=[
                        58.395,
                        57.12,
                        57.375,
                    ],
                    to_rgb=True,
                    type='Normalize'),
                dict(
                    backend_args=None,
                    coord_type='LIDAR',
                    load_dim=4,
                    type='LoadPointsFromFile',
                    use_dim=4),
                dict(
                    flip=False,
                    img_scale=(
                        1333,
                        800,
                    ),
                    pts_scale_ratio=1,
                    transforms=[
                        dict(
                            rot_range=[
                                0,
                                0,
                            ],
                            scale_ratio_range=[
                                1.0,
                                1.0,
                            ],
                            translation_std=[
                                0,
                                0,
                                0,
                            ],
                            type='GlobalRotScaleTrans'),
                        dict(type='RandomFlip3D'),
                        dict(
                            point_cloud_range=[
                                0,
                                -39.68,
                                -3,
                                69.12,
                                39.68,
                                1,
                            ],
                            type='PointsRangeFilter'),
                    ],
                    type='MultiScaleFlipAug3D'),
                dict(keys=[
                    'points',
                    'img',
                ], type='Pack3DDetInputs'),
            ],
            test_mode=True,
            type='KittiDataset'),
        drop_last=False,
        num_workers=1,
        persistent_workers=True,
        sampler=dict(shuffle=False, type='DefaultSampler')),
    train=dict(
        batch_size=2,
        dataset=dict(
            dataset=dict(
                ann_file='kitti_infos_train.pkl',
                backend_args=None,
                box_type_3d='LiDAR',
                data_prefix=dict(
                    img='training/image_2', pts='training/velodyne_reduced'),
                data_root='data/kitti/',
                metainfo=dict(classes=[
                    'Car',
                ]),
                modality=dict(use_camera=True, use_lidar=True),
                pipeline=[
                    dict(type='mmcv.LoadImageFromFile'),
                    dict(keep_ratio=False, scale=(
                        1280,
                        384,
                    ), type='Resize'),
                    dict(
                        mean=[
                            123.675,
                            116.28,
                            103.53,
                        ],
                        std=[
                            58.395,
                            57.12,
                            57.375,
                        ],
                        to_rgb=True,
                        type='Normalize'),
                    dict(
                        backend_args=None,
                        coord_type='LIDAR',
                        load_dim=4,
                        type='LoadPointsFromFile',
                        use_dim=4),
                    dict(
                        type='LoadAnnotations3D',
                        with_bbox_3d=True,
                        with_label_3d=True),
                    dict(
                        db_sampler=dict(
                            backend_args=None,
                            classes=[
                                'Car',
                            ],
                            data_root='data/kitti/',
                            info_path='data/kitti/kitti_dbinfos_train.pkl',
                            points_loader=dict(
                                backend_args=None,
                                coord_type='LIDAR',
                                load_dim=4,
                                type='LoadPointsFromFile',
                                use_dim=4),
                            prepare=dict(
                                filter_by_difficulty=[
                                    -1,
                                ],
                                filter_by_min_points=dict(Car=5)),
                            rate=1.0,
                            sample_groups=dict(Car=15)),
                        type='ObjectSample',
                        use_ground_plane=False),
                    dict(flip_ratio_bev_horizontal=0.5, type='RandomFlip3D'),
                    dict(
                        rot_range=[
                            -0.78539816,
                            0.78539816,
                        ],
                        scale_ratio_range=[
                            0.95,
                            1.05,
                        ],
                        type='GlobalRotScaleTrans'),
                    dict(
                        point_cloud_range=[
                            0,
                            -39.68,
                            -3,
                            69.12,
                            39.68,
                            1,
                        ],
                        type='PointsRangeFilter'),
                    dict(
                        point_cloud_range=[
                            0,
                            -39.68,
                            -3,
                            69.12,
                            39.68,
                            1,
                        ],
                        type='ObjectRangeFilter'),
                    dict(type='PointShuffle'),
                    dict(
                        keys=[
                            'points',
                            'gt_labels_3d',
                            'gt_bboxes_3d',
                            'img',
                            'gt_bboxes',
                            'gt_labels',
                        ],
                        type='Pack3DDetInputs'),
                ],
                test_mode=False,
                type='KittiDataset'),
            times=2,
            type='RepeatDataset'),
        num_workers=4,
        persistent_workers=True,
        sampler=dict(shuffle=True, type='DefaultSampler')),
    val=dict(
        batch_size=1,
        dataset=dict(
            ann_file='kitti_infos_val.pkl',
            backend_args=None,
            box_type_3d='LiDAR',
            data_prefix=dict(
                img='training/image_2', pts='training/velodyne_reduced'),
            data_root='data/kitti/',
            metainfo=dict(classes=[
                'Car',
            ]),
            modality=dict(use_camera=True, use_lidar=True),
            pipeline=[
                dict(type='mmcv.LoadImageFromFile'),
                dict(keep_ratio=False, scale=(
                    1280,
                    384,
                ), type='Resize'),
                dict(
                    mean=[
                        123.675,
                        116.28,
                        103.53,
                    ],
                    std=[
                        58.395,
                        57.12,
                        57.375,
                    ],
                    to_rgb=True,
                    type='Normalize'),
                dict(
                    backend_args=None,
                    coord_type='LIDAR',
                    load_dim=4,
                    type='LoadPointsFromFile',
                    use_dim=4),
                dict(
                    flip=False,
                    img_scale=(
                        1333,
                        800,
                    ),
                    pts_scale_ratio=1,
                    transforms=[
                        dict(
                            rot_range=[
                                0,
                                0,
                            ],
                            scale_ratio_range=[
                                1.0,
                                1.0,
                            ],
                            translation_std=[
                                0,
                                0,
                                0,
                            ],
                            type='GlobalRotScaleTrans'),
                        dict(type='RandomFlip3D'),
                        dict(
                            point_cloud_range=[
                                0,
                                -39.68,
                                -3,
                                69.12,
                                39.68,
                                1,
                            ],
                            type='PointsRangeFilter'),
                    ],
                    type='MultiScaleFlipAug3D'),
                dict(keys=[
                    'points',
                    'img',
                ], type='Pack3DDetInputs'),
            ],
            test_mode=True,
            type='KittiDataset'),
        drop_last=False,
        num_workers=1,
        persistent_workers=True,
        sampler=dict(shuffle=False, type='DefaultSampler')))
data_root = 'data/kitti/'
dataset_type = 'KittiDataset'
db_sampler = dict(
    backend_args=None,
    classes=[
        'Car',
    ],
    data_root='data/kitti/',
    info_path='data/kitti/kitti_dbinfos_train.pkl',
    points_loader=dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=4,
        type='LoadPointsFromFile',
        use_dim=4),
    prepare=dict(
        filter_by_difficulty=[
            -1,
        ],
        filter_by_min_points=dict(Car=5, Cyclist=5, Pedestrian=5)),
    rate=1.0,
    sample_groups=dict(Car=15, Cyclist=15, Pedestrian=15))
'''
default_hooks = dict(
    checkpoint=dict(interval=1, type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(type='Det3DVisualizationHook'))
'''
default_hooks = dict(
    checkpoint=dict(type='CheckpointHook', interval=1),
    visualization=dict(
        type='Det3DVisualizationHook',
        draw=True,
        interval=1
    )
)
default_scope = 'mmdet3d'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
epoch_num = 80
eval_pipeline = [
    dict(type='mmcv.LoadImageFromFile'),
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=4,
        type='LoadPointsFromFile',
        use_dim=4),
    dict(keys=[
        'points',
        'img',
    ], type='Pack3DDetInputs'),
]
input_modality = dict(use_camera=True, use_lidar=True)
launcher = 'slurm'
load_from = None
log_config = dict(
    hooks=[
        dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook'),
        dict(type='JSONLoggerHook'),
    ],
    interval=10)
log_level = 'DEBUG'
log_processor = dict(by_epoch=True, type='LogProcessor', window_size=50)
lr = 0.001
metainfo = dict(classes=[
    'Car',
])
model = dict(
    bbox_head=dict(
        anchor_generator=dict(
            ranges=[
                [
                    0,
                    -39.68,
                    -1.78,
                    69.12,
                    39.68,
                    -1.78,
                ],
            ],
            reshape_out=True,
            rotations=[
                0,
                1.57,
            ],
            sizes=[
                [
                    3.9,
                    1.6,
                    1.56,
                ],
            ],
            type='AlignedAnchor3DRangeGenerator'),
        assign_per_class=True,
        bbox_coder=dict(type='DeltaXYZWLHRBBoxCoder'),
        diff_rad_by_sin=True,
        feat_channels=256,
        in_channels=256,
        loss_bbox=dict(
            beta=0.1111111111111111,
            loss_weight=2.0,
            type='mmdet.SmoothL1Loss'),
        loss_cls=dict(
            alpha=0.25,
            gamma=2.0,
            loss_weight=1.0,
            type='mmdet.FocalLoss',
            use_sigmoid=True),
        loss_dir=dict(
            loss_weight=0.2, type='mmdet.CrossEntropyLoss', use_sigmoid=False),
        num_classes=1,
        type='Anchor3DHead',
        use_direction_classifier=True),
    data_preprocessor=dict(
        type='Det3DDataPreprocessor',
        voxel=True,
        voxel_layer=dict(
            max_num_points=32,
            max_voxels=(
                16000,
                40000,
            ),
            point_cloud_range=[
                0,
                -39.68,
                -3,
                69.12,
                39.68,
                1,
            ],
            voxel_size=[
                0.16,
                0.16,
                4,
            ])),
    fusion_module = dict(
        type='TransformerFusionMBT',
        d_model=256,
        num_heads=8,
        mlp_ratio=4,
        feature_size=32,            # pooled spatial size
        in_img_channels=256,
        in_lidar_channels=384,      # match your neck concat
        num_bottleneck_tokens=32,   # small T (MBT-style)
        num_layers=2,               # stack a couple of masked layers
        attn_dropout=0.0,
        proj_dropout=0.0,
    ),
    img_backbone=dict(
        depth=18,
        frozen_stages=1,
        norm_cfg=dict(requires_grad=False, type='BN'),
        norm_eval=True,
        num_stages=4,
        out_indices=(
            0,
            1,
            2,
            3,
        ),
        type='mmdet.ResNet',
        with_cp=True,
        zero_init_residual=False),
    img_bbox_head=dict(
        feat_channels=256,
        in_channels=64,
        loss_bbox=dict(type='mmdet.IoULoss'),
        loss_cls=dict(
            alpha=0.25,
            gamma=2.0,
            loss_weight=1.0,
            type='mmdet.FocalLoss',
            use_sigmoid=True),
        loss_l1=dict(type='mmdet.L1Loss'),
        loss_obj=dict(type='mmdet.CrossEntropyLoss'),
        num_classes=3,
        strides=[
            16,
        ],
        test_cfg=dict(
            max_per_img=100,
            nms=dict(iou_threshold=0.65, type='nms'),
            score_thr=0.01),
        type='mmdet.YOLOXHead'),
    img_neck=dict(
        add_extra_convs=True,
        in_channels=[
            64,
            128,
            256,
            512,
        ],
        num_outs=5,
        out_channels=256,
        type='mmdet.FPN'),
    lidar_backbone=dict(
        in_channels=64,
        layer_nums=[
            3,
            5,
            5,
        ],
        layer_strides=[
            2,
            2,
            2,
        ],
        out_channels=[
            64,
            128,
            256,
        ],
        type='SECOND'),
    lidar_middle_encoder=dict(
        in_channels=64, output_shape=[
            496,
            432,
        ], type='PointPillarsScatter'),
    lidar_neck=dict(
        in_channels=[
            64,
            128,
            256,
        ],
        out_channels=[
            128,
            128,
            128,
        ],
        type='SECONDFPN',
        upsample_strides=[
            1,
            2,
            4,
        ]),
    lidar_voxel_encoder=dict(
        feat_channels=[
            64,
        ],
        in_channels=4,
        point_cloud_range=[
            0,
            -39.68,
            -3,
            69.12,
            39.68,
            1,
        ],
        type='PillarFeatureNet',
        voxel_size=[
            0.16,
            0.16,
            4,
        ],
        with_distance=False),
    test_cfg=dict(
        max_num=50,
        min_bbox_size=0,
        nms_across_levels=False,
        nms_pre=100,
        nms_thr=0.01,
        score_thr=0.1,
        use_rotate_nms=True),
    train_cfg=dict(
        allowed_border=0,
        assigner=dict(
            ignore_iof_thr=-1,
            iou_calculator=dict(type='BboxOverlapsNearest3D'),
            min_pos_iou=0.45,
            neg_iou_thr=0.45,
            pos_iou_thr=0.6,
            type='Max3DIoUAssigner'),
        debug=False,
        pos_weight=-1),
    type='MyFusionTransformer')
model_wrapper_cfg = dict(
    find_unused_parameters=True,
    static_graph=True,
    type='MMDistributedDataParallel')
number_of_channels = 64
optim_wrapper = dict(
    clip_grad=dict(max_norm=35, norm_type=2),
    optimizer=dict(
        betas=(
            0.95,
            0.99,
        ), lr=0.001, type='AdamW', weight_decay=0.01),
    type='OptimWrapper')
param_scheduler = [
    dict(
        T_max=32.0,
        begin=0,
        by_epoch=True,
        convert_to_iter_based=True,
        end=32.0,
        eta_min=0.01,
        type='CosineAnnealingLR'),
    dict(
        T_max=48.0,
        begin=32.0,
        by_epoch=True,
        convert_to_iter_based=True,
        end=80,
        eta_min=1.0000000000000001e-07,
        type='CosineAnnealingLR'),
    dict(
        T_max=32.0,
        begin=0,
        by_epoch=True,
        convert_to_iter_based=True,
        end=32.0,
        eta_min=0.8947368421052632,
        type='CosineAnnealingMomentum'),
    dict(
        T_max=48.0,
        begin=32.0,
        convert_to_iter_based=True,
        end=80,
        eta_min=1,
        type='CosineAnnealingMomentum'),
]
point_cloud_range = [
    0,
    -39.68,
    -3,
    69.12,
    39.68,
    1,
]
resume = False
test_cfg = dict()
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='kitti_infos_val.pkl',
        backend_args=None,
        box_type_3d='LiDAR',
        data_prefix=dict(
            img='training/image_2', pts='training/velodyne_reduced'),
        data_root='data/kitti/',
        metainfo=dict(classes=[
            'Car',
        ]),
        modality=dict(use_camera=True, use_lidar=True),
        pipeline=[
            dict(type='mmcv.LoadImageFromFile'),
            dict(keep_ratio=False, scale=(
                1280,
                384,
            ), type='Resize'),
            dict(
                mean=[
                    123.675,
                    116.28,
                    103.53,
                ],
                std=[
                    58.395,
                    57.12,
                    57.375,
                ],
                to_rgb=True,
                type='Normalize'),
            dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=4,
                type='LoadPointsFromFile',
                use_dim=4),
            dict(
                flip=False,
                img_scale=(
                    1333,
                    800,
                ),
                pts_scale_ratio=1,
                transforms=[
                    dict(
                        rot_range=[
                            0,
                            0,
                        ],
                        scale_ratio_range=[
                            1.0,
                            1.0,
                        ],
                        translation_std=[
                            0,
                            0,
                            0,
                        ],
                        type='GlobalRotScaleTrans'),
                    dict(type='RandomFlip3D'),
                    dict(
                        point_cloud_range=[
                            0,
                            -39.68,
                            -3,
                            69.12,
                            39.68,
                            1,
                        ],
                        type='PointsRangeFilter'),
                ],
                type='MultiScaleFlipAug3D'),
            dict(keys=[
                'points',
                'img',
            ], type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='KittiDataset'),
    drop_last=False,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    ann_file='data/kitti/kitti_infos_val.pkl',
    backend_args=None,
    metric='bbox',
    pklfile_prefix='work_dirs/kitti_test_results/',
    prefix='work_dirs/kitti_test_results/',
    type='KittiMetric')
test_pipeline = [
    dict(type='mmcv.LoadImageFromFile'),
    dict(keep_ratio=False, scale=(
        1280,
        384,
    ), type='Resize'),
    dict(
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        std=[
            58.395,
            57.12,
            57.375,
        ],
        to_rgb=True,
        type='Normalize'),
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=4,
        type='LoadPointsFromFile',
        use_dim=4),
    dict(
        flip=False,
        img_scale=(
            1333,
            800,
        ),
        pts_scale_ratio=1,
        transforms=[
            dict(
                rot_range=[
                    0,
                    0,
                ],
                scale_ratio_range=[
                    1.0,
                    1.0,
                ],
                translation_std=[
                    0,
                    0,
                    0,
                ],
                type='GlobalRotScaleTrans'),
            dict(type='RandomFlip3D'),
            dict(
                point_cloud_range=[
                    0,
                    -39.68,
                    -3,
                    69.12,
                    39.68,
                    1,
                ],
                type='PointsRangeFilter'),
        ],
        type='MultiScaleFlipAug3D'),
    dict(keys=[
        'points',
        'img',
    ], type='Pack3DDetInputs'),
]
train_cfg = dict(by_epoch=True, max_epochs=80, val_interval=2)
train_dataloader = dict(
    batch_size=2,
    dataset=dict(
        dataset=dict(
            ann_file='kitti_infos_train.pkl',
            backend_args=None,
            box_type_3d='LiDAR',
            data_prefix=dict(
                img='training/image_2', pts='training/velodyne_reduced'),
            data_root='data/kitti/',
            metainfo=dict(classes=[
                'Car',
            ]),
            modality=dict(use_camera=True, use_lidar=True),
            pipeline=[
                dict(type='mmcv.LoadImageFromFile'),
                dict(keep_ratio=False, scale=(
                    1280,
                    384,
                ), type='Resize'),
                dict(
                    mean=[
                        123.675,
                        116.28,
                        103.53,
                    ],
                    std=[
                        58.395,
                        57.12,
                        57.375,
                    ],
                    to_rgb=True,
                    type='Normalize'),
                dict(
                    backend_args=None,
                    coord_type='LIDAR',
                    load_dim=4,
                    type='LoadPointsFromFile',
                    use_dim=4),
                dict(
                    type='LoadAnnotations3D',
                    with_bbox_3d=True,
                    with_label_3d=True),
                dict(
                    db_sampler=dict(
                        backend_args=None,
                        classes=[
                            'Car',
                        ],
                        data_root='data/kitti/',
                        info_path='data/kitti/kitti_dbinfos_train.pkl',
                        points_loader=dict(
                            backend_args=None,
                            coord_type='LIDAR',
                            load_dim=4,
                            type='LoadPointsFromFile',
                            use_dim=4),
                        prepare=dict(
                            filter_by_difficulty=[
                                -1,
                            ],
                            filter_by_min_points=dict(Car=5)),
                        rate=1.0,
                        sample_groups=dict(Car=15)),
                    type='ObjectSample',
                    use_ground_plane=False),
                dict(flip_ratio_bev_horizontal=0.5, type='RandomFlip3D'),
                dict(
                    rot_range=[
                        -0.78539816,
                        0.78539816,
                    ],
                    scale_ratio_range=[
                        0.95,
                        1.05,
                    ],
                    type='GlobalRotScaleTrans'),
                dict(
                    point_cloud_range=[
                        0,
                        -39.68,
                        -3,
                        69.12,
                        39.68,
                        1,
                    ],
                    type='PointsRangeFilter'),
                dict(
                    point_cloud_range=[
                        0,
                        -39.68,
                        -3,
                        69.12,
                        39.68,
                        1,
                    ],
                    type='ObjectRangeFilter'),
                dict(type='PointShuffle'),
                dict(
                    keys=[
                        'points',
                        'gt_labels_3d',
                        'gt_bboxes_3d',
                        'img',
                        'gt_bboxes',
                        'gt_labels',
                    ],
                    type='Pack3DDetInputs'),
            ],
            test_mode=False,
            type='KittiDataset'),
        times=2,
        type='RepeatDataset'),
    num_workers=4,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(type='mmcv.LoadImageFromFile'),
    dict(keep_ratio=False, scale=(
        1280,
        384,
    ), type='Resize'),
    dict(
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        std=[
            58.395,
            57.12,
            57.375,
        ],
        to_rgb=True,
        type='Normalize'),
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=4,
        type='LoadPointsFromFile',
        use_dim=4),
    dict(type='LoadAnnotations3D', with_bbox_3d=True, with_label_3d=True),
    dict(
        db_sampler=dict(
            backend_args=None,
            classes=[
                'Car',
            ],
            data_root='data/kitti/',
            info_path='data/kitti/kitti_dbinfos_train.pkl',
            points_loader=dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=4,
                type='LoadPointsFromFile',
                use_dim=4),
            prepare=dict(
                filter_by_difficulty=[
                    -1,
                ], filter_by_min_points=dict(Car=5)),
            rate=1.0,
            sample_groups=dict(Car=15)),
        type='ObjectSample',
        use_ground_plane=True),
    dict(flip_ratio_bev_horizontal=0.5, type='RandomFlip3D'),
    dict(
        rot_range=[
            -0.78539816,
            0.78539816,
        ],
        scale_ratio_range=[
            0.95,
            1.05,
        ],
        type='GlobalRotScaleTrans'),
    dict(
        point_cloud_range=[
            0,
            -39.68,
            -3,
            69.12,
            39.68,
            1,
        ],
        type='PointsRangeFilter'),
    dict(
        point_cloud_range=[
            0,
            -39.68,
            -3,
            69.12,
            39.68,
            1,
        ],
        type='ObjectRangeFilter'),
    dict(type='PointShuffle'),
    dict(
        keys=[
            'points',
            'gt_labels_3d',
            'gt_bboxes_3d',
            'img',
            'gt_bboxes',
            'gt_labels',
        ],
        type='Pack3DDetInputs'),
]
val_cfg = dict()
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='kitti_infos_val.pkl',
        backend_args=None,
        box_type_3d='LiDAR',
        data_prefix=dict(
            img='training/image_2', pts='training/velodyne_reduced'),
        data_root='data/kitti/',
        metainfo=dict(classes=[
            'Car',
        ]),
        modality=dict(use_camera=True, use_lidar=True),
        pipeline=[
            dict(type='mmcv.LoadImageFromFile'),
            dict(keep_ratio=False, scale=(
                1280,
                384,
            ), type='Resize'),
            dict(
                mean=[
                    123.675,
                    116.28,
                    103.53,
                ],
                std=[
                    58.395,
                    57.12,
                    57.375,
                ],
                to_rgb=True,
                type='Normalize'),
            dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=4,
                type='LoadPointsFromFile',
                use_dim=4),
            dict(
                flip=False,
                img_scale=(
                    1333,
                    800,
                ),
                pts_scale_ratio=1,
                transforms=[
                    dict(
                        rot_range=[
                            0,
                            0,
                        ],
                        scale_ratio_range=[
                            1.0,
                            1.0,
                        ],
                        translation_std=[
                            0,
                            0,
                            0,
                        ],
                        type='GlobalRotScaleTrans'),
                    dict(type='RandomFlip3D'),
                    dict(
                        point_cloud_range=[
                            0,
                            -39.68,
                            -3,
                            69.12,
                            39.68,
                            1,
                        ],
                        type='PointsRangeFilter'),
                ],
                type='MultiScaleFlipAug3D'),
            dict(keys=[
                'points',
                'img',
            ], type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='KittiDataset'),
    drop_last=False,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    ann_file='data/kitti/kitti_infos_val.pkl',
    backend_args=None,
    metric='bbox',
    pklfile_prefix='work_dirs/kitti_eval_results/',
    prefix='work_dirs/kitti_eval_results/',
    type='KittiMetric')
vis_backends = [
    dict(type='LocalVisBackend'),
    dict(type='TensorboardVisBackend'),
]
'''

visualizer = dict(
    name='visualizer',
    save_dir='work_dirs/visualizations',
    type='Det3DLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
        dict(type='TensorboardVisBackend'),
    ])
'''
visualizer = dict(
    type='Det3DLocalVisualizer',
    vis_backends=[dict(type='LocalVisBackend')],
    save_dir='/home/abhiramannaluru/vis_epochX'  # change per run if you want
)

voxel_size = [
    0.16,
    0.16,
    4,
]
work_dir = 'work_dirs/train_my_fusion_pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car_slurm'
